package com.snowshock35.packfixer.utils;

import com.snowshock35.packfixer.PackFixer;
import cpw.mods.fml.common.ModMetadata;

public class MetadataHelper {
    public static ModMetadata transformMetadata(ModMetadata meta) {
        meta.authorList.clear();
        meta.authorList.add("SnowShock35");
        meta.modId = PackFixer.MOD_ID;
        meta.name = PackFixer.MOD_NAME;
        meta.version = PackFixer.MOD_VERSION;
        meta.description = PackFixer.MOD_DESC;
        meta.url = PackFixer.MOD_URL;
        meta.credits = PackFixer.MOD_CREDITS;
        meta.logoFile = PackFixer.MOD_LOGO_PATH;
        meta.autogenerated = false;
        return meta;
    }
}